apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: aws-creds
  namespace: cert-manager
  type: "Opaque"
  literals:
  - aws_access_key_id=MY_AWS_ACCESS_KEY_ID
  - aws_secret_access_key=MY_AWS_SECRET_ACCESS_KEY

resources:
  - public-issuer.yaml
  - self-signed-issuer.yaml