apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: aws-creds
  namespace: cert-manager
  files:
  - aws_secret_access_key=aws_access_key
  - aws_secret_access_key=aws_secret_access_key

resources:
  - public-issuer.yaml
  - self-signed-issuer.yaml