apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: public-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acm-cicd@redhat.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: haproxy
        selector:
          matchLabels:
            "use-http01-solver": "true"
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-east-1
            accessKeyID: MY_AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: aws-creds
              key: aws_secret_access_key
        selector:
          matchLabels:
            "use-dns01-solver": "true"